const express = require("express");
const router = express.Router();
const ctrlUser = require("../controllers/user.controller");
const jwtHelper = require("../config/jwtHelper");
router.post("/register", ctrlUser.register);
router.post("/authenticate", ctrlUser.authenticate);
router.get("/userProfile", jwtHelper.verifyJwtToken, ctrlUser.userProfile);
router.put("/edituser/:id", ctrlUser.edituser);
router.delete("/deleteUser/:id", ctrlUser.deleteUser);
module.exports = router;
